# Generated by Django 5.0.2 on 2024-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceschedule",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
