# Generated by Django 5.0.2 on 2024-02-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0004_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceschedule",
            name="technique",
            field=models.CharField(
                choices=[
                    ("Technique1", "Electrique"),
                    ("Technique2", "Mecanique"),
                    ("Technique3", "Pneumatique"),
                    ("Technique3", "Logiciel"),
                    ("Technique3", "Autre"),
                ],
                default="Technique1",
                max_length=20,
            ),
        ),
    ]
