# Generated by Django 5.0.2 on 2024-02-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0006_maintenanceschedule_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceschedule",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("Type1", "Preventive"),
                    ("Type2", "Corrective"),
                    ("Type3", "Predictive"),
                ],
                default="Type1",
                max_length=20,
            ),
        ),
    ]
