# Generated by Django 5.0.2 on 2024-02-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0007_maintenanceschedule_maintenance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="m_model",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="m_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
