# Generated by Django 5.0.2 on 2024-02-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0008_machine_m_model_machine_m_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceschedule",
            name="duration_hours",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
