# Generated by Django 5.0.2 on 2024-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0011_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceRechange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_piece", models.CharField(max_length=255)),
                ("modele", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "fournisseur",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantite", models.PositiveIntegerField(default=0)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=8)),
                ("seuil_minimum", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "emplacement_stockage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_achat", models.DateField(blank=True, null=True)),
                ("garantie_mois", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
