# Generated by Django 5.0.2 on 2024-02-28 13:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0012_piecerechange"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="equipment",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="equipment",
            name="effective_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="equipment",
            name="model",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(default="Unknown", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="vendor",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="equipment",
            name="vendor_reference",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="warranty_expiration",
            field=models.DateField(default=datetime.date(2026, 1, 1)),
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maintenance_app.equipmentcategory",
            ),
        ),
        migrations.CreateModel(
            name="PreventiveMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_frequency_days", models.IntegerField()),
                ("maintenance_duration", models.DurationField()),
                ("expected_mean_time_between_failures", models.DurationField()),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance_app.equipment",
                    ),
                ),
            ],
        ),
    ]
