# Generated by Django 5.0.2 on 2024-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "maintenance_app",
            "0014_equipment_used_by_correctivemaintenance_technician_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="piecerechange",
            name="prix",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
