# Generated by Django 5.0.2 on 2024-03-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0016_correctivemaintenance_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="preventive_maintenance",
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="corrective_maintenance_entries",
            field=models.ManyToManyField(
                blank=True, to="maintenance_app.correctivemaintenance"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="maintenance_type",
            field=models.CharField(
                choices=[("corrective", "Corrective Maintenance")], max_length=10
            ),
        ),
    ]
