# Generated by Django 5.0.2 on 2024-03-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "maintenance_app",
            "0017_remove_maintenancerequest_preventive_maintenance_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="equipment",
        ),
    ]
