# Generated by Django 5.0.2 on 2024-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0018_remove_maintenancerequest_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="guest",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
