# Generated by Django 5.0.2 on 2024-03-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0019_technician_guest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technician",
            name="guest",
        ),
    ]
