# Generated by Django 5.0.2 on 2024-03-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0020_remove_technician_guest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correctivemaintenance",
            name="end_time",
        ),
    ]
