# Generated by Django 5.0.2 on 2024-03-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0021_remove_correctivemaintenance_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preventivemaintenance",
            name="maintenance_duration",
        ),
        migrations.RemoveField(
            model_name="preventivemaintenance",
            name="name",
        ),
        migrations.AddField(
            model_name="preventivemaintenance",
            name="activity",
            field=models.CharField(default="ACTIVITY -", max_length=50),
        ),
        migrations.AddField(
            model_name="preventivemaintenance",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
