# Generated by Django 5.0.2 on 2024-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0023_preventivemaintenance_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctivemaintenance",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
