# Generated by Django 5.0.2 on 2024-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_app", "0024_correctivemaintenance_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctivemaintenance",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="correctivemaintenance",
            name="scheduled_date",
            field=models.DateTimeField(),
        ),
    ]
